[[redirects]]
  from = "/"
  to = "https://dahisea.github.io/GF-WWW/"
  status = 200
  force = true

[[redirects]]
  from = "/favicon.ico"
  to = "https://thepage-gfork.zh-hk.eu.org/favicon.ico"
  status = 301
  force = true

[[redirects]]
  from = "/p/1E3F8A9F-DDC6-4D76-B101-5683AA13E349"
  to = "https://dgkkhxhkj.dahi.edu.eu.org/zh-CN/scripts.json"
  status = 200

[[redirects]]
  from = "/*"
  to = "https://cdn-1-mod-agf.zh-cn.eu.org/:splat"
  status = 200
